import ctypes as ctypes
import os as os
import sys as sys
import warnings as warnings

import tensorrt_libs as tensorrt_libs
from tensorrt_bindings.tensorrt import (
    ActivationType,
    AllocatorFlag,
    APILanguage,
    AttentionIOForm,
    AttentionNormalizationOp,
    BoundingBoxFormat,
    Builder,
    BuilderFlag,
    CausalMaskKind,
    CollectiveOperation,
    CumulativeOperation,
    DataType,
    DeviceType,
    DimensionOperation,
    Dims,
    Dims2,
    Dims3,
    Dims4,
    DimsExprs,
    DimsHW,
    DynamicPluginTensorDesc,
    ElementWiseOperation,
    EngineCapability,
    EngineInspector,
    EngineStat,
    ErrorCode,
    ErrorCodeTRT,
    ExecutionContextAllocationStrategy,
    FallbackString,
    FillOperation,
    GatherMode,
    HardwareCompatibilityLevel,
    IActivationLayer,
    IAssertionLayer,
    IAttention,
    IAttentionBoundaryLayer,
    IAttentionInputLayer,
    IAttentionOutputLayer,
    IBuilderConfig,
    ICastLayer,
    IConcatenationLayer,
    IConditionLayer,
    IConstantLayer,
    IConvolutionLayer,
    ICudaEngine,
    ICumulativeLayer,
    IDebugListener,
    IDeconvolutionLayer,
    IDequantizeLayer,
    IDimensionExpr,
    IDistCollectiveLayer,
    IDynamicQuantizeLayer,
    IEinsumLayer,
    IElementWiseLayer,
    IErrorRecorder,
    IExecutionContext,
    IExprBuilder,
    IFillLayer,
    IGatherLayer,
    IGpuAllocator,
    IGpuAsyncAllocator,
    IGridSampleLayer,
    IHostMemory,
    IIdentityLayer,
    IIfConditional,
    IIfConditionalBoundaryLayer,
    IIfConditionalInputLayer,
    IIfConditionalOutputLayer,
    IIteratorLayer,
    IKVCacheUpdateLayer,
    ILayer,
    ILogger,
    ILoop,
    ILoopBoundaryLayer,
    ILoopOutputLayer,
    ILRNLayer,
    IMatrixMultiplyLayer,
    IMoELayer,
    INetworkDefinition,
    INMSLayer,
    INonZeroLayer,
    INormalizationLayer,
    InterfaceInfo,
    InterpolationMode,
    IOneHotLayer,
    IOptimizationProfile,
    IOutputAllocator,
    IPaddingLayer,
    IParametricReLULayer,
    IPluginCapability,
    IPluginCreator,
    IPluginCreatorInterface,
    IPluginCreatorV3One,
    IPluginCreatorV3Quick,
    IPluginRegistry,
    IPluginResource,
    IPluginResourceContext,
    IPluginV2,
    IPluginV2DynamicExt,
    IPluginV2DynamicExtBase,
    IPluginV2Ext,
    IPluginV2Layer,
    IPluginV3,
    IPluginV3Layer,
    IPluginV3OneBuild,
    IPluginV3OneBuildV2,
    IPluginV3OneCore,
    IPluginV3OneRuntime,
    IPluginV3QuickAOTBuild,
    IPluginV3QuickBuild,
    IPluginV3QuickCore,
    IPluginV3QuickRuntime,
    IPoolingLayer,
    IProfiler,
    IProgressMonitor,
    IQuantizeLayer,
    IRaggedSoftMaxLayer,
    IRecurrenceLayer,
    IReduceLayer,
    IResizeLayer,
    IReverseSequenceLayer,
    IRotaryEmbeddingLayer,
    IRuntimeConfig,
    IScaleLayer,
    IScatterLayer,
    ISelectLayer,
    ISerializationConfig,
    IShapeLayer,
    IShuffleLayer,
    ISliceLayer,
    ISoftMaxLayer,
    ISqueezeLayer,
    IStreamReaderV2,
    IStreamWriter,
    ISymExpr,
    ISymExprs,
    ITensor,
    ITimingCache,
    ITopKLayer,
    ITripLimitLayer,
    IUnaryLayer,
    IUnsqueezeLayer,
    IVersionedInterface,
    KernelLaunchParams,
    KVCacheMode,
    LayerInformationFormat,
    LayerType,
    Logger,
    LoopOutput,
    MatrixOperation,
    MemoryPoolType,
    MoEActType,
    NetworkDefinitionCreationFlag,
    NodeIndices,
    OnnxParser,
    OnnxParserFlag,
    OnnxParserRefitter,
    PaddingMode,
    ParserError,
    Permutation,
    PluginArgDataType,
    PluginArgType,
    PluginCapabilityType,
    PluginCreatorVersion,
    PluginField,
    PluginFieldCollection,
    PluginFieldCollection_,
    PluginFieldType,
    PluginTensorDesc,
    PoolingType,
    PreviewFeature,
    Profiler,
    ProfilingVerbosity,
    QuickPluginCreationRequest,
    ReduceOperation,
    Refitter,
    ResizeCoordinateTransformation,
    ResizeRoundMode,
    ResizeSelector,
    Runtime,
    RuntimePlatform,
    SampleMode,
    ScaleMode,
    ScatterMode,
    SeekPosition,
    SerializationFlag,
    TacticSource,
    TempfileControlFlag,
    TensorFormat,
    TensorIOMode,
    TensorLocation,
    TensorRTPhase,
    TilingOptimizationLevel,
    TimingCacheKey,
    TimingCacheValue,
    TopKOperation,
    TripLimit,
    UnaryOperation,
    Weights,
    WeightsRole,
    get_builder_plugin_registry,
    get_nv_onnx_parser_version,
    get_plugin_registry,
    init_libnvinfer_plugins,
)

from . import tensorrt

__all__: list[str] = [
    "APILanguage",
    "ActivationType",
    "AllocatorFlag",
    "AttentionIOForm",
    "AttentionNormalizationOp",
    "BoundingBoxFormat",
    "Builder",
    "BuilderFlag",
    "CausalMaskKind",
    "CollectiveOperation",
    "CumulativeOperation",
    "DataType",
    "DeviceType",
    "DimensionOperation",
    "Dims",
    "Dims2",
    "Dims3",
    "Dims4",
    "DimsExprs",
    "DimsHW",
    "DynamicPluginTensorDesc",
    "ElementWiseOperation",
    "EngineCapability",
    "EngineInspector",
    "EngineStat",
    "ErrorCode",
    "ErrorCodeTRT",
    "ExecutionContextAllocationStrategy",
    "FallbackString",
    "FillOperation",
    "GatherMode",
    "HardwareCompatibilityLevel",
    "IActivationLayer",
    "IAssertionLayer",
    "IAttention",
    "IAttentionBoundaryLayer",
    "IAttentionInputLayer",
    "IAttentionOutputLayer",
    "IBuilderConfig",
    "ICastLayer",
    "IConcatenationLayer",
    "IConditionLayer",
    "IConstantLayer",
    "IConvolutionLayer",
    "ICudaEngine",
    "ICumulativeLayer",
    "IDebugListener",
    "IDeconvolutionLayer",
    "IDequantizeLayer",
    "IDimensionExpr",
    "IDistCollectiveLayer",
    "IDynamicQuantizeLayer",
    "IEinsumLayer",
    "IElementWiseLayer",
    "IErrorRecorder",
    "IExecutionContext",
    "IExprBuilder",
    "IFillLayer",
    "IGatherLayer",
    "IGpuAllocator",
    "IGpuAsyncAllocator",
    "IGridSampleLayer",
    "IHostMemory",
    "IIdentityLayer",
    "IIfConditional",
    "IIfConditionalBoundaryLayer",
    "IIfConditionalInputLayer",
    "IIfConditionalOutputLayer",
    "IIteratorLayer",
    "IKVCacheUpdateLayer",
    "ILRNLayer",
    "ILayer",
    "ILogger",
    "ILoop",
    "ILoopBoundaryLayer",
    "ILoopOutputLayer",
    "IMatrixMultiplyLayer",
    "IMoELayer",
    "INMSLayer",
    "INetworkDefinition",
    "INonZeroLayer",
    "INormalizationLayer",
    "IOneHotLayer",
    "IOptimizationProfile",
    "IOutputAllocator",
    "IPaddingLayer",
    "IParametricReLULayer",
    "IPluginCapability",
    "IPluginCreator",
    "IPluginCreatorInterface",
    "IPluginCreatorV3One",
    "IPluginCreatorV3Quick",
    "IPluginRegistry",
    "IPluginResource",
    "IPluginResourceContext",
    "IPluginV2",
    "IPluginV2DynamicExt",
    "IPluginV2DynamicExtBase",
    "IPluginV2Ext",
    "IPluginV2Layer",
    "IPluginV3",
    "IPluginV3Layer",
    "IPluginV3OneBuild",
    "IPluginV3OneBuildV2",
    "IPluginV3OneCore",
    "IPluginV3OneRuntime",
    "IPluginV3QuickAOTBuild",
    "IPluginV3QuickBuild",
    "IPluginV3QuickCore",
    "IPluginV3QuickRuntime",
    "IPoolingLayer",
    "IProfiler",
    "IProgressMonitor",
    "IQuantizeLayer",
    "IRaggedSoftMaxLayer",
    "IRecurrenceLayer",
    "IReduceLayer",
    "IResizeLayer",
    "IReverseSequenceLayer",
    "IRotaryEmbeddingLayer",
    "IRuntimeConfig",
    "IScaleLayer",
    "IScatterLayer",
    "ISelectLayer",
    "ISerializationConfig",
    "IShapeLayer",
    "IShuffleLayer",
    "ISliceLayer",
    "ISoftMaxLayer",
    "ISqueezeLayer",
    "IStreamReaderV2",
    "IStreamWriter",
    "ISymExpr",
    "ISymExprs",
    "ITensor",
    "ITimingCache",
    "ITopKLayer",
    "ITripLimitLayer",
    "IUnaryLayer",
    "IUnsqueezeLayer",
    "IVersionedInterface",
    "InterfaceInfo",
    "InterpolationMode",
    "KVCacheMode",
    "KernelLaunchParams",
    "LayerInformationFormat",
    "LayerType",
    "Logger",
    "LoopOutput",
    "MatrixOperation",
    "MemoryPoolType",
    "MoEActType",
    "NetworkDefinitionCreationFlag",
    "NodeIndices",
    "OnnxParser",
    "OnnxParserFlag",
    "OnnxParserRefitter",
    "PaddingMode",
    "ParserError",
    "Permutation",
    "PluginArgDataType",
    "PluginArgType",
    "PluginCapabilityType",
    "PluginCreatorVersion",
    "PluginField",
    "PluginFieldCollection",
    "PluginFieldCollection_",
    "PluginFieldType",
    "PluginTensorDesc",
    "PoolingType",
    "PreviewFeature",
    "Profiler",
    "ProfilingVerbosity",
    "QuickPluginCreationRequest",
    "ReduceOperation",
    "Refitter",
    "ResizeCoordinateTransformation",
    "ResizeRoundMode",
    "ResizeSelector",
    "Runtime",
    "RuntimePlatform",
    "SampleMode",
    "ScaleMode",
    "ScatterMode",
    "SeekPosition",
    "SerializationFlag",
    "TacticSource",
    "TempfileControlFlag",
    "TensorFormat",
    "TensorIOMode",
    "TensorLocation",
    "TensorRTPhase",
    "TilingOptimizationLevel",
    "TimingCacheKey",
    "TimingCacheValue",
    "TopKOperation",
    "TripLimit",
    "UnaryOperation",
    "Weights",
    "WeightsRole",
    "attr",
    "bfloat16",
    "bool",
    "common_enter",
    "common_exit",
    "ctypes",
    "e8m0",
    "float16",
    "float32",
    "fp4",
    "fp8",
    "get_builder_plugin_registry",
    "get_nv_onnx_parser_version",
    "get_plugin_registry",
    "init_libnvinfer_plugins",
    "int4",
    "int8",
    "int32",
    "int64",
    "nptype",
    "os",
    "sys",
    "tensorrt",
    "tensorrt_libs",
    "uint8",
    "value",
    "volume",
    "warnings",
]

def _itemsize(trt_type):
    """

    Returns the size in bytes of this :class:`DataType`.
    The returned size is a rational number, possibly a `Real` denoting a fraction of a byte.

    :arg trt_type: The TensorRT data type.

    :returns: The size of the type.
    """

def common_enter(this): ...
def common_exit(this, exc_type, exc_value, traceback):
    """

    Context managers are deprecated and have no effect. Objects are automatically freed when
    the reference count reaches 0.
    """

def nptype(trt_type):
    """

    Returns the numpy-equivalent of a TensorRT :class:`DataType` .

    :arg trt_type: The TensorRT data type to convert.

    :returns: The equivalent numpy type.
    """

def volume(iterable):
    """

    Computes the volume of an iterable.

    :arg iterable: Any python iterable, including a :class:`Dims` object.

    :returns: The volume of the iterable. This will return 1 for empty iterables, as a scalar has an empty shape and the volume of a tensor with empty shape is 1.
    """

__version__: str = "11.0.0.114"
attr: str = "VERBOSE"
bfloat16: tensorrt.DataType  # value = <DataType.BF16: 7>
bool: tensorrt.DataType  # value = <DataType.BOOL: 4>
e8m0: tensorrt.DataType  # value = <DataType.E8M0: 11>
float16: tensorrt.DataType  # value = <DataType.HALF: 1>
float32: tensorrt.DataType  # value = <DataType.FLOAT: 0>
fp4: tensorrt.DataType  # value = <DataType.FP4: 10>
fp8: tensorrt.DataType  # value = <DataType.FP8: 6>
int32: tensorrt.DataType  # value = <DataType.INT32: 3>
int4: tensorrt.DataType  # value = <DataType.INT4: 9>
int64: tensorrt.DataType  # value = <DataType.INT64: 8>
int8: tensorrt.DataType  # value = <DataType.INT8: 2>
uint8: tensorrt.DataType  # value = <DataType.UINT8: 5>
value: tensorrt.ILogger.Severity  # value = <Severity.VERBOSE: 4>
