from _typeshed import Incomplete

class OnnxGraphContext:
    stopping_initializers: Incomplete
    initializers: Incomplete
    tensor_to_node: Incomplete
    variables: Incomplete
    def __init__(self, graph_proto, nodelist) -> None: ...
    def add_value_of_node(self, name, value) -> None: ...
    @staticmethod
    def get_attribute(node, attr_name, default_value=None): ...
    @staticmethod
    def get_attr_graph(node): ...
    def calculate(self, node): ...

def reserve_node_for_embedded_graph(nodelist: onnx.GraphProto) -> tuple[onnx.GraphProto, frozenset]: ...
def const_folding_optimizer(graph: onnx.GraphProto, outer_graph: onnx.GraphProto = None) -> onnx.GraphProto: ...
