from _typeshed import Incomplete
from onnxconverter_common import float16 as float16

def auto_convert_mixed_precision(model, feed_dict, validate_fn=None, rtol=None, atol=None, keep_io_types: bool = False): ...
def add_missing_dtypes_using_ort(model, feed_dict, outputs_per_iter: int = 100): ...
def get_tensor_values_using_ort(model, input_feed, output_names=None, sess_options=None): ...

class SegmentList:
    node_names: Incomplete
    first: Incomplete
    def __init__(self, node_names) -> None: ...
    def get_largest(self, adjacent_to_good: bool = False): ...
    def get_nodes(self, node_segment=None): ...

class NodeSegment:
    size: Incomplete
    next: Incomplete
    good: bool
    bad: bool
    def __init__(self, size) -> None: ...
    def split(self) -> None: ...
