from _typeshed import Incomplete

from .interface import ModelContainer as ModelContainer

class RawModelContainer:
    def __init__(self, raw_model) -> None: ...
    @property
    def raw_model(self): ...
    @property
    def input_names(self) -> None: ...
    @property
    def output_names(self) -> None: ...

class CommonSklearnModelContainer(RawModelContainer):
    def __init__(self, sklearn_model) -> None: ...
    @property
    def input_names(self): ...
    @property
    def output_names(self): ...
    def add_input(self, variable) -> None: ...
    def add_output(self, variable) -> None: ...

class LightGbmModelContainer(CommonSklearnModelContainer): ...
class XGBoostModelContainer(CommonSklearnModelContainer): ...

class ModelComponentContainer(ModelContainer):
    inputs: Incomplete
    outputs: Incomplete
    initializers: Incomplete
    value_info: Incomplete
    nodes: Incomplete
    node_domain_version_pair_sets: Incomplete
    target_opset: Incomplete
    enable_optimizer: bool
    def __init__(self, target_opset) -> None: ...
    def add_input(self, variable) -> None: ...
    def add_output(self, variable) -> None: ...
    def add_initializer(self, name, onnx_type, shape, content) -> None: ...
    def add_value_info(self, variable) -> None: ...
    def add_node(self, op_type, inputs, outputs, op_domain: str = "", op_version: int = 1, **attrs) -> None: ...
