from _typeshed import Incomplete

class DataType:
    shape: Incomplete
    doc_string: Incomplete
    def __init__(self, shape=None, doc_string: str = "") -> None: ...
    def to_onnx_type(self) -> None: ...

class Int64Type(DataType):
    def __init__(self, doc_string: str = "") -> None: ...
    def to_onnx_type(self): ...

class FloatType(DataType):
    def __init__(self, doc_string: str = "") -> None: ...
    def to_onnx_type(self): ...

class StringType(DataType):
    def __init__(self, doc_string: str = "") -> None: ...
    def to_onnx_type(self): ...

class TensorType(DataType):
    denotation: Incomplete
    channel_denotations: Incomplete
    def __init__(self, shape=None, doc_string: str = "", denotation=None, channel_denotations=None) -> None: ...
    def to_onnx_type(self): ...

class Int32TensorType(TensorType):
    def __init__(self, shape=None, doc_string: str = "") -> None: ...

class Int8TensorType(TensorType):
    def __init__(self, shape=None, doc_string: str = "") -> None: ...

class UInt8TensorType(TensorType):
    def __init__(self, shape=None, doc_string: str = "") -> None: ...

class Int64TensorType(TensorType):
    def __init__(self, shape=None, doc_string: str = "") -> None: ...

class BooleanTensorType(TensorType):
    def __init__(self, shape=None, doc_string: str = "") -> None: ...

class FloatTensorType(TensorType):
    color_space: Incomplete
    def __init__(
        self, shape=None, color_space=None, doc_string: str = "", denotation=None, channel_denotations=None
    ) -> None: ...

class DoubleTensorType(TensorType):
    color_space: Incomplete
    def __init__(self, shape=None, color_space=None, doc_string: str = "") -> None: ...

class Complex64TensorType(TensorType):
    color_space: Incomplete
    def __init__(self, shape=None, color_space=None, doc_string: str = "") -> None: ...

class Complex128TensorType(TensorType):
    color_space: Incomplete
    def __init__(self, shape=None, color_space=None, doc_string: str = "") -> None: ...

class StringTensorType(TensorType):
    def __init__(self, shape=None, doc_string: str = "") -> None: ...

class DictionaryType(DataType):
    key_type: Incomplete
    value_type: Incomplete
    def __init__(self, key_type, value_type, shape=None, doc_string: str = "") -> None: ...
    def to_onnx_type(self): ...

class SequenceType(DataType):
    element_type: Incomplete
    doc_string: Incomplete
    def __init__(self, element_type, shape=None, doc_string: str = "") -> None: ...
    def to_onnx_type(self): ...

def find_type_conversion(source_type, target_type): ...
def onnx_built_with_ml(): ...
