from _typeshed import Incomplete
from onnx import onnx_pb as onnx_proto

FLOAT32: int
FLOAT16: int

def convert_np_to_float16(np_array, min_positive_val: float = 1e-07, max_finite_val: float = 10000.0): ...
def convert_tensor_float_to_float16(tensor, min_positive_val: float = 1e-07, max_finite_val: float = 10000.0): ...
def make_value_info_from_tensor(tensor): ...

DEFAULT_OP_BLOCK_LIST: Incomplete

def initial_checking(model, disable_shape_infer): ...
def convert_float_to_float16(
    model,
    min_positive_val: float = 1e-07,
    max_finite_val: float = 10000.0,
    keep_io_types: bool = False,
    disable_shape_infer: bool = False,
    op_block_list=None,
    node_block_list=None,
    check_fp16_ready: bool = True,
): ...
def process_node_input_output(graph: onnx_proto.GraphProto, global_input_name_dict: dict): ...
def process_graph_input(
    graph: onnx_proto.GraphProto, is_top_level: bool, is_io_fp32: bool, global_input_name_dict: dict
): ...
def process_graph_output(graph: onnx_proto.GraphProto, is_top_level: bool, is_io_fp32: bool): ...
def process_node_in_block_list(
    graph: onnx_proto.GraphProto, global_input_name_dict: dict, op_block_list: list, node_block_list: list
): ...
def insert_cast32_before_node(graph: onnx_proto.GraphProto, node: onnx_proto.NodeProto, global_input_name_dict): ...
def insert_cast16_after_node(graph: onnx_proto.GraphProto, node: onnx_proto.NodeProto, global_input_name_dict): ...
def process_tensor_in_node(
    graph: onnx_proto.GraphProto, op_block_list: list, node_block_list: list, min_positive_val, max_finite_val
): ...
def process_value_info(graph: onnx_proto.GraphProto, value_info_block_list: list): ...
def process_initializers(
    graph: onnx_proto.GraphProto, op_block_list, node_block_list, min_positive_val, max_finite_val
): ...
def get_next_level_graph(graph: onnx_proto.GraphProto, op_block_list: list, node_block_list: list): ...
def add_cast_node(graph: onnx_proto.GraphProto, inputs: list, outputs: list, node_name: str, to_type: int): ...
def add_new_value_info(
    graph: onnx_proto.GraphProto, exist_value_info: onnx_proto.ValueInfoProto, name: str, dtype: int
): ...
def find_upstream_node_by_output_name(graph: onnx_proto.GraphProto, output_name: str): ...
def find_donwstream_node_by_input_name(graph: onnx_proto.GraphProto, input_name: str): ...
def remove_identity_node_from_model(model: onnx_proto.ModelProto): ...
def remove_identity_node_from_graph(graph: onnx_proto.GraphProto): ...
def convert_float_to_float16_model_path(
    model_path, min_positive_val: float = 1e-07, max_finite_val: float = 10000.0, keep_io_types: bool = False
): ...
def sort_graph_node(graph_proto): ...
def sort_topology(graph_proto) -> None: ...
def remove_unnecessary_cast_node(graph_proto: onnx_proto.GraphProto): ...
def check_if_fp16_ready(graph_proto): ...
