def apply_abs(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_add(scope, input_names, output_name, container, operator_name=None, axis=None, broadcast=None) -> None: ...
def apply_argmax(scope, input_name, output_name, container, operator_name=None, axis: int = 0, keepdims: int = 1, select_last_index: int = 0) -> None: ...
def apply_argmin(scope, input_name, output_name, container, operator_name=None, axis: int = 0, keepdims: int = 1, select_last_index: int = 0) -> None: ...
def apply_affine(scope, input_name, output_name, container, operator_name=None, alpha: float = 1.0, beta: float = 0.0) -> None: ...
def apply_batch_norm(scope, input_names, output_names, container, operator_name=None, epsilon=None, is_test=None, momentum=None, spatial=None) -> None: ...
def apply_cast(scope, input_name, output_name, container, operator_name=None, to=None) -> None: ...
def apply_clip(scope, input_name, output_name, container, operator_name=None, max=None, min=None) -> None: ...
def apply_concat(scope, input_names, output_name, container, operator_name=None, axis: int = 0) -> None: ...
def apply_constant(scope, output_name, container, operator_name=None, value=None) -> None: ...
def apply_constant2(scope, input_names, output_name, container, operator_name=None, value=None): ...
def apply_constant_of_shape(scope, input_names, output_name, container, operator_name=None, value=None) -> None: ...
def apply_conv(scope, input_names, output_name, container, operator_name=None, **attrs) -> None: ...
def apply_crop_height_width(scope, input_name, output_name, container, operator_name=None, top_border: int = 0, bottom_border: int = 0, left_border: int = 0, right_border: int = 0) -> None: ...
def apply_div(scope, input_names, output_name, container, operator_name=None, axis=None, broadcast=None) -> None: ...
def apply_elu(scope, input_name, output_name, container, operator_name=None, alpha: float = 1.0) -> None: ...
def apply_equal(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_exp(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_floor(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_flatten(scope, input_name, output_name, container, operator_name=None, axis: int = 1) -> None: ...
def apply_gather(scope, input_names, output_name, container, operator_name=None, axis: int = 0) -> None: ...
def apply_gemm(scope, input_name, output_name, container, operator_name=None, alpha: float = 1.0, beta: float = 1.0, transA: int = 0, transB: int = 0) -> None: ...
def apply_greater(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_greater_or_equal(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_less_or_equal(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_gru(scope, input_names, output_names, container, operator_name=None, output_seq: int = 0, reset_after: int = 0, **attrs) -> None: ...
def apply_hard_sigmoid(scope, input_name, output_name, container, operator_name=None, alpha=None, beta=None) -> None: ...
def apply_identity(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_instance_norm(scope, input_names, output_name, container, operator_name=None, epsilon: float = 1e-05) -> None: ...
def apply_inverse(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_leaky_relu(scope, input_name, output_name, container, operator_name=None, alpha: float = 0.01) -> None: ...
def apply_less(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_log(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_lstm(scope, input_names, output_names, container, operator_name=None, output_seq: int = 0, **attrs) -> None: ...
def apply_matmul(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_max(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_mean(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_min(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_mul(scope, input_names, output_name, container, operator_name=None, axis=None, broadcast=None) -> None: ...
def apply_neg(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_normalization(scope, input_name, output_name, container, operator_name=None, axis: int = 1, p: int = 2) -> None: ...
def apply_not_op(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_pad(scope, input_name, output_name, container, operator_name=None, mode=None, pads=None, value=None, onnx_type=...) -> None: ...
def apply_parametric_softplus(scope, input_name, output_name, container, operator_name=None, alpha=None, beta=None) -> None: ...
def apply_pow(scope, input_names, output_name, container, operator_name=None, axis=None, broadcast=None) -> None: ...
def apply_prelu(scope, input_name, output_name, container, operator_name=None, slope=None) -> None: ...
def apply_range(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_reciprocal(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_reducesum(scope, input_name, output_name, container, operator_name=None, axes=None, keepdims: int = 1, rank: int = 0) -> None: ...
def apply_relu(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_relu_6(scope, input_name, output_name, container, operator_name=None, zero_value: float = 0.0) -> None: ...
def apply_reshape(scope, input_name, output_name, container, operator_name=None, desired_shape=None) -> None: ...
def apply_resize(scope, input_name, output_name, container, operator_name=None, mode: str = 'nearest', coordinate_transformation_mode: str = 'asymmetric', scales=None) -> None: ...
def apply_rnn(scope, input_names, output_names, container, operator_name=None, output_seq: int = 0, **attrs) -> None: ...
def apply_shape(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_sigmoid(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_softsign(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_selu(scope, input_name, output_name, container, operator_name=None, alpha: float = 1.673263, gamma: float = 1.050701) -> None: ...
def apply_softmax(scope, input_name, output_name, container, operator_name=None, axis=None) -> None: ...
def apply_scaled_tanh(scope, input_name, output_name, container, operator_name=None, alpha=None, beta=None) -> None: ...
def apply_slice(scope, input_name, output_name, container, starts, ends, axes=None, steps=None, operator_name=None) -> None: ...
def apply_slice2(scope, input_name, output_name, container, operator_name=None, starts=None, ends=None, axes=None, steps=None): ...
def apply_split(scope, input_name, output_names, container, operator_name=None, split=None, axis: int = 0) -> None: ...
def apply_sqrt(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_squeeze(scope, input_name, output_name, container, operator_name=None, axes=None, rank: int = 0) -> None: ...
def apply_sub(scope, input_names, output_name, container, operator_name=None, axis=None, broadcast: int = 0) -> None: ...
def apply_sum(scope, input_names, output_name, container, operator_name=None) -> None: ...
def apply_tanh(scope, input_name, output_name, container, operator_name=None) -> None: ...
def apply_thresholded_relu(scope, input_name, output_name, container, operator_name=None, alpha=None) -> None: ...
def apply_tile(scope, input_name, output_name, container, operator_name=None, repeats=None) -> None: ...
def apply_topk(scope, input_name, output_names, container, k, operator_name=None) -> None: ...
def apply_transpose(scope, input_name, output_name, container, operator_name=None, perm=None) -> None: ...
def apply_upsample(scope, input_name, output_name, container, operator_name=None, mode: str = 'nearest', coordinate_transformation_mode: str = 'asymmetric', scales=None) -> None: ...
def apply_unsqueeze(scope, input_name, output_name, container, operator_name=None, axes=None, rank: int = 0) -> None: ...
