from _typeshed import Incomplete

from .pytracing import TracingObject as TracingObject

needed_types: Incomplete
const_dir: Incomplete
const_counter: Incomplete
np_traced: Incomplete
helper_traced: Incomplete
numpy_helper_traced: Incomplete
TensorProtoTraced: Incomplete
os_traced: Incomplete

def clear_field(proto, field): ...
def order_repeated_field(repeated_proto, key_name, order): ...
def make_external_tensor(name, data_type, dims, raw_data=None, **kwargs): ...
def make_node(op_type, inputs, outputs, name=None, doc_string=None, domain=None, **kwargs): ...
def make_graph(*args, doc_string=None, **kwargs): ...

clear_field_traced: Incomplete
make_external_tensor_traced: Incomplete
make_node_traced: Incomplete
make_graph_traced: Incomplete
DATA_DIR_TRACED: Incomplete

def convert_tensor_type(i): ...
def convert_field(field): ...
def convert_value_info(val_info): ...
def convert_operatorsetid(opsetid): ...
def convert_external_tensor(tensor): ...
def convert_tensor(tensor): ...
def convert_node(node): ...
def convert_graph(graph): ...
def convert_model(model): ...
def clear_directory(path) -> None: ...

class MissingHandlerException(Exception): ...

FILE_HEADER: str

def convert(model, out_path): ...
def main() -> None: ...
