from _typeshed import Incomplete

from . import onnx_ops as onnx_ops
from .data_types import BooleanTensorType as BooleanTensorType
from .data_types import Complex64TensorType as Complex64TensorType
from .data_types import Complex128TensorType as Complex128TensorType
from .data_types import DoubleTensorType as DoubleTensorType
from .data_types import FloatTensorType as FloatTensorType
from .data_types import Int32TensorType as Int32TensorType
from .data_types import Int64TensorType as Int64TensorType
from .data_types import StringTensorType as StringTensorType
from .onnx_ex import OPSET_TO_IR_VERSION as OPSET_TO_IR_VERSION
from .onnx_ex import get_maximum_opset_supported as get_maximum_opset_supported
from .oopb import OnnxOperatorBuilder as OnnxOperatorBuilder
from .registration import register_converter as register_converter
from .topology import Topology as Topology
from .topology import convert_topology as convert_topology

class GraphFunctionType:
    D = DoubleTensorType
    F = FloatTensorType
    I = Int64TensorType
    B = BooleanTensorType
    I32 = Int32TensorType
    C64 = Complex64TensorType
    C128 = Complex128TensorType
    S = StringTensorType
    d: Incomplete
    f: Incomplete
    i: Incomplete
    i32: Incomplete
    b: Incomplete
    c64: Incomplete
    c128: Incomplete
    s: Incomplete

class _SimpleRawModelContainer:
    input_names: Incomplete
    output_names: Incomplete
    def __init__(self, inputs, outputs) -> None: ...

class Graph:
    opset: Incomplete
    inference_runtime: Incomplete
    def __init__(self, name) -> None: ...
    @property
    def oxml(self): ...
    @property
    def name(self): ...
    def to_model(self): ...
    @staticmethod
    def trace(*args, **kwargs): ...
    def __call__(self, *args, **kwargs): ...
    def save(self, path) -> None: ...
    @staticmethod
    def load(path_or_model, name=None, inputs=None, outputs=None): ...

class Tensor:
    name: Incomplete
    ox: Incomplete
    def __init__(self, tensor_name: str, ox) -> None: ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    def __div__(self, other): ...
    def __pow__(self, other): ...
    def __matmul__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __neg__(self): ...
    def __not__(self): ...
    def __getitem__(self, indices): ...
    def __getattribute__(self, attr): ...

class OnnxOperatorBuilderX(OnnxOperatorBuilder):
    def apply_op(self, apply_func_or_op_type, inputs, name=None, outputs=None, **attrs): ...
    def apply_invoke_inline(self, ox_graph, input_map, output_map): ...
    def arg(self, name): ...
    def loop(self, count, cond, body, inputs, outputs=None, name=None): ...
