import types

from _typeshed import Incomplete

from . import onnx_ops as onnx_ops

class _OperatorNameContext:
    basename: Incomplete
    oopb: Incomplete
    def __init__(self, oopb, basename) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class OnnxOperatorBuilder:
    basename: Incomplete
    upper_ctx: Incomplete
    int32: Incomplete
    int64: Incomplete
    float: Incomplete
    float16: Incomplete
    double: Incomplete
    bool: Incomplete
    def __init__(self, container, scope) -> None: ...
    def as_default(self, basename): ...
    @property
    def upper_context(self): ...
    @staticmethod
    def value_to_ndarray(value): ...
    def add_node(self, op_type, inputs, name=None, outputs=None, op_domain: str = "", op_version=None, **attrs): ...
    def add_node_with_output(self, op_type, inputs, outputs, name, op_domain: str = "", op_version=None, **attrs): ...
    def apply_op(self, apply_func, inputs, name=None, outputs=None, **attrs): ...
    def constant(self, name=None, value=None, outputs=None): ...
    def constant_of_shape(self, inputs, name=None, outputs=None, value=None): ...
    def slice(self, inputs, name=None, outputs=None, starts=None, ends=None, axes=None, steps=None): ...
    def loop(self, trip_count, cond, body, inputs, outputs, name=None): ...
    def abs(self, inputs, name=None, outputs=None): ...
    def add(self, inputs, name=None, outputs=None, axis=None, broadcast=None): ...
    def argmax(self, inputs, name=None, outputs=None, axis: int = 0, keepdims: int = 1, select_last_index: int = 0): ...
    def argmin(self, inputs, name=None, outputs=None, axis: int = 0, keepdims: int = 1, select_last_index: int = 0): ...
    def affine(self, inputs, name=None, outputs=None, alpha: float = 1.0, beta: float = 0.0): ...
    def batch_norm(self, inputs, name=None, outputs=None, epsilon=None, is_test=None, momentum=None, spatial=None): ...
    def cast(self, inputs, name=None, outputs=None, to=None): ...
    def clip(self, inputs, name=None, outputs=None, max=None, min=None): ...
    def concat(self, inputs, name=None, outputs=None, axis: int = 0): ...
    def conv(self, inputs, name=None, outputs=None): ...
    def crop_height_width(self, inputs, name=None, outputs=None, top_border: int = 0, bottom_border: int = 0, left_border: int = 0, right_border: int = 0): ...
    def div(self, inputs, name=None, outputs=None, axis=None, broadcast=None): ...
    def elu(self, inputs, name=None, outputs=None, alpha: float = 1.0): ...
    def equal(self, inputs, name=None, outputs=None): ...
    def exp(self, inputs, name=None, outputs=None): ...
    def floor(self, inputs, name=None, outputs=None): ...
    def flatten(self, inputs, name=None, outputs=None, axis: int = 1): ...
    def gather(self, inputs, name=None, outputs=None, axis: int = 0): ...
    def gemm(self, inputs, name=None, outputs=None, alpha: float = 1.0, beta: float = 1.0, transA: int = 0, transB: int = 0): ...
    def greater(self, inputs, name=None, outputs=None): ...
    def greater_or_equal(self, inputs, name=None, outputs=None): ...
    def less_or_equal(self, inputs, name=None, outputs=None): ...
    def gru(self, inputs, name=None, outputs=None, output_seq: int = 0, reset_after: int = 0): ...
    def hard_sigmoid(self, inputs, name=None, outputs=None, alpha=None, beta=None): ...
    def identity(self, inputs, name=None, outputs=None): ...
    def instance_norm(self, inputs, name=None, outputs=None, epsilon: float = 1e-05): ...
    def inverse(self, inputs, name=None, outputs=None): ...
    def leaky_relu(self, inputs, name=None, outputs=None, alpha: float = 0.01): ...
    def less(self, inputs, name=None, outputs=None): ...
    def log(self, inputs, name=None, outputs=None): ...
    def lstm(self, inputs, name=None, outputs=None, output_seq: int = 0): ...
    def matmul(self, inputs, name=None, outputs=None): ...
    def max(self, inputs, name=None, outputs=None): ...
    def mean(self, inputs, name=None, outputs=None): ...
    def min(self, inputs, name=None, outputs=None): ...
    def mul(self, inputs, name=None, outputs=None, axis=None, broadcast=None): ...
    def neg(self, inputs, name=None, outputs=None): ...
    def normalization(self, inputs, name=None, outputs=None, axis: int = 1, p: int = 2): ...
    def not_op(self, inputs, name=None, outputs=None): ...
    def pad(self, inputs, name=None, outputs=None, mode=None, pads=None, value=None, onnx_type: int = 1): ...
    def parametric_softplus(self, inputs, name=None, outputs=None, alpha=None, beta=None): ...
    def pow(self, inputs, name=None, outputs=None, axis=None, broadcast=None): ...
    def prelu(self, inputs, name=None, outputs=None, slope=None): ...
    def range(self, inputs, name=None, outputs=None): ...
    def reciprocal(self, inputs, name=None, outputs=None): ...
    def reducesum(self, inputs, name=None, outputs=None, axes=None, keepdims: int = 1, rank: int = 0): ...
    def relu(self, inputs, name=None, outputs=None): ...
    def relu_6(self, inputs, name=None, outputs=None, zero_value: float = 0.0): ...
    def reshape(self, inputs, name=None, outputs=None, desired_shape=None): ...
    def resize(self, inputs, name=None, outputs=None, mode: str = "nearest", coordinate_transformation_mode: str = "asymmetric", scales=None): ...
    def rnn(self, inputs, name=None, outputs=None, output_seq: int = 0): ...
    def shape(self, inputs, name=None, outputs=None): ...
    def sigmoid(self, inputs, name=None, outputs=None): ...
    def softsign(self, inputs, name=None, outputs=None): ...
    def selu(self, inputs, name=None, outputs=None, alpha: float = 1.673263, gamma: float = 1.050701): ...
    def softmax(self, inputs, name=None, outputs=None, axis=None): ...
    def scaled_tanh(self, inputs, name=None, outputs=None, alpha=None, beta=None): ...
    def slice2(self, inputs, name=None, outputs=None, starts=None, ends=None, axes=None, steps=None): ...
    def split(self, inputs, name=None, outputs=None, split=None, axis: int = 0): ...
    def sqrt(self, inputs, name=None, outputs=None): ...
    def squeeze(self, inputs, name=None, outputs=None, axes=None, rank: int = 0): ...
    def sub(self, inputs, name=None, outputs=None, axis=None, broadcast: int = 0): ...
    def sum(self, inputs, name=None, outputs=None): ...
    def tanh(self, inputs, name=None, outputs=None): ...
    def thresholded_relu(self, inputs, name=None, outputs=None, alpha=None): ...
    def tile(self, inputs, name=None, outputs=None, repeats=None): ...
    def transpose(self, inputs, name=None, outputs=None, perm=None): ...
    def upsample(self, inputs, name=None, outputs=None, mode: str = "nearest", coordinate_transformation_mode: str = "asymmetric", scales=None): ...
    def unsqueeze(self, inputs, name=None, outputs=None, axes=None, rank: int = 0): ...
