from ._opt_const_folding import OnnxGraphContext as OnnxGraphContext, const_folding_optimizer as const_folding_optimizer, reserve_node_for_embedded_graph as reserve_node_for_embedded_graph
from _typeshed import Incomplete
from onnx import onnx_pb as onnx_proto

class LinkedNode:
    reserved_names_in_graph: Incomplete
    origin: onnx_proto.NodeProto
    input: Incomplete
    output: Incomplete
    tensors: Incomplete
    initializers: Incomplete
    precedence: Incomplete
    successor: Incomplete
    attributes: Incomplete
    unique_name: Incomplete
    target_opset: Incomplete
    def __init__(self, node=None, in_n=None, out_n=None, tensors_n=None, target_opset=None) -> None: ...
    @property
    def op_type(self): ...
    @property
    def name(self): ...
    @property
    def is_identity(self): ...
    @property
    def is_transpose(self): ...
    @property
    def in_single_path(self): ...
    @property
    def in_single_path_to_output(self): ...
    @property
    def element_wise(self): ...
    @property
    def broadcast(self): ...
    @property
    def in_single_path_and_inner(self): ...
    @property
    def in_simo_and_inner(self): ...
    @property
    def in_miso_and_inner(self): ...
    @property
    def in_mi_and_inner(self): ...
    @property
    def is_eligible_concat_and_inner(self): ...
    @property
    def is_transpose_switchable(self): ...
    @property
    def is_transpose_switchable_single_path(self): ...
    @property
    def is_transpose_switchable_simo(self): ...
    @property
    def is_transpose_switchable_miso(self): ...
    @property
    def is_transpose_switchable_mi(self): ...
    @property
    def in_or_out(self): ...
    @property
    def single_input(self): ...
    @property
    def single_origin_input(self): ...
    @property
    def single_output(self): ...
    @property
    def single_origin_output(self): ...
    @property
    def is_reserved(self): ...
    def in_redirect(self, old_name, name) -> None: ...
    def out_redirect(self, old_name, name) -> None: ...
    def get_input_by_idx(self, idx: int = 0): ...
    def get_output_by_idx(self, idx: int = 0): ...
    def get_precedence_by_idx(self, idx: int = 0): ...
    def get_precedence_tensor_by_idx(self, idx: int = 0): ...
    def get_attribute(self, attr_name, default_value=None): ...
    def generate(self): ...
    def add_precedence(self, pre, tname) -> None: ...
    @staticmethod
    def build_from_onnx(onnx_nodes, nchw_inputs, inputs, outputs, initializers=None, target_opset=None): ...
    @staticmethod
    def debug_print(node_list) -> None: ...

class Solution:
    begin: Incomplete
    begin_n: Incomplete
    end_p: Incomplete
    end: Incomplete
    def __init__(self, begin, begin_n, end_p, end) -> None: ...
    @staticmethod
    def get_perm(onode): ...
    @staticmethod
    def is_useless_transpose(perm): ...
    @staticmethod
    def delete_node_nto1(node_list: [], begin: LinkedNode, node: LinkedNode, end: LinkedNode) -> []: ...
    @staticmethod
    def delete_node_1ton(node_list: [], begin: LinkedNode, node: LinkedNode, end: LinkedNode) -> []: ...
    @staticmethod
    def add_siso_node(node_list: [], begin: LinkedNode, end: LinkedNode, begin_output_name: str, node: LinkedNode) -> []: ...
    def apply(self, node_list): ...

def match_perm(perm0, perm1): ...

class MergeSolution(Solution):
    def apply(self, node_list): ...

class MoveForwardSolution(Solution):
    def apply(self, node_list): ...

class FanOutSolution(Solution):
    number: int
    def apply(self, node_list): ...

class TransposeFanOutSolution(Solution):
    def apply(self, node_list): ...

class FanInSolution(Solution):
    number: int
    perm: Incomplete
    def __init__(self, begin, begin_n, end_p, end, perm) -> None: ...
    def apply(self, node_list): ...

class MergePadConvSolution(Solution):
    def __init__(self, begin, begin_n, end_p, end) -> None: ...
    def apply(self, node_list): ...

class MergePadTransposeConvSolution(Solution):
    def __init__(self, begin, begin_n, end_p, end) -> None: ...
    def apply(self, node_list): ...

class NextToOutputSolution(Solution):
    def apply(self, node_list): ...

class ConvBatchNormSolution(Solution):
    def __init__(self, begin, begin_n, end_p, end) -> None: ...
    def apply(self, node_list): ...

class RedundantOptimizer:
    @staticmethod
    def find(node): ...

class MergePadConvOptimizer:
    @staticmethod
    def find(node): ...

class MergePadTransposeConvOptimizer:
    @staticmethod
    def find(node): ...

class ConvBatchNormOptimizer:
    @staticmethod
    def find(node): ...

class MergeReshapeTransposeSolution(Solution):
    init_number: int
    def __init__(self, begin, begin_n, end_p, end) -> None: ...
    def apply(self, node_list): ...

class MergeReshapeOptimizer:
    @staticmethod
    def find(node): ...

class MergeCastOptimizer:
    to_priority_array: Incomplete
    @staticmethod
    def find(node): ...

class MergeSqueezeUnsqueezeOptimizer:
    @staticmethod
    def find(node): ...

class PushTransposeSolution(Solution):
    transpose_number: int
    def __init__(self, begin, begin_n, end_p, end) -> None: ...
    def apply(self, node_list): ...

class TransposeOptimizer:
    @staticmethod
    def find_local(node): ...
    @staticmethod
    def find_push_down(node): ...
    @staticmethod
    def find(node): ...

class SwapOpSolution(Solution):
    def apply(self, node_list): ...

class SwapOpOptimizer:
    @staticmethod
    def find(node): ...

class MergeCommonSequenceSolution(Solution):
    def apply(self, node_list): ...

class MergeCommonSequenceOptimizer:
    @staticmethod
    def find(node): ...
    @staticmethod
    def is_same_node_merge(node_0, node_1, node): ...

class MatmulSolution(Solution):
    basic_transpose: Incomplete
    def apply(self, node_list): ...

class MatmulOptimizer:
    @staticmethod
    def find(node: LinkedNode) -> Union[Solution, None]: ...

def optimize_onnx(onnx_nodes, nchw_inputs=None, inputs=None, outputs=None, target_opset=None): ...
def optimize_onnx_graph(onnx_nodes, nchw_inputs=None, inputs=None, outputs=None, initializers=None, stop_initializers=None, model_value_info=None, model_name=None, target_opset=None): ...
def optimize_onnx_model(origin_model: onnx.ModelProto, nchw_inputs: list = None, stop_initializers: list = None) -> onnx.ModelProto: ...
