from _typeshed import Incomplete

raw_entry_headers: Incomplete
raw_entry_col_widths: Incomplete
RawEntry: Incomplete
node_entry_headers: Incomplete
node_entry_col_widths: Incomplete
NodeEntry: Incomplete
step_entry_headers: Incomplete
step_entry_col_widths: Incomplete
StepEntry: Incomplete
type_entry_headers: Incomplete
type_entry_col_widths: Incomplete
OpTypeEntry: Incomplete

def compute_step_entries(raw_entries): ...
def compute_node_entries(raw_entries): ...
def compute_op_type_entries(raw_entries): ...
def read_raw_entries(profile_path): ...
def get_args(): ...

class QueryClause:
    rule_type: str
    match_name: Incomplete
    match_type: Incomplete
    patterns: Incomplete
    def __init__(self, clause_string) -> None: ...
    def match(self, entry): ...

class Query:
    clauses: Incomplete
    no_inc: Incomplete
    def __init__(self, query_string) -> None: ...
    def match(self, entry): ...

class TablePrinter:
    col_widths: Incomplete
    unknown_cnt: Incomplete
    padding: Incomplete
    fixed_sum: Incomplete
    min_width: Incomplete
    def __init__(self, col_widths, padding: int = 2, min_width: int = 5) -> None: ...
    def get_col_widths(self, total_width): ...
    def format(self, entry, width): ...
    def print_divider(self) -> None: ...
    def print(self, entries) -> None: ...

def main() -> None: ...
