def indent(s): ...

class NoPyObjException(Exception):
    def __init__(self) -> None: ...

class TracingObject:
    def __init__(self, trace, py_obj=...) -> None: ...
    @staticmethod
    def reset_cnt(o) -> None: ...
    @staticmethod
    def get_cnt(o): ...
    @staticmethod
    def from_repr(o): ...
    @staticmethod
    def get_repr(x): ...
    @staticmethod
    def get_py_obj(o): ...
    def __getattr__(self, attr): ...
    def __call__(self, *args, **kwargs): ...
