def register_converter(operator_name, conversion_function, overwrite: bool = False) -> None: ...
def get_converter(operator_name): ...
def register_shape_calculator(operator_name, calculator_function, overwrite: bool = False) -> None: ...
def get_shape_calculator(operator_name): ...
