from .data_types import DictionaryType as DictionaryType, FloatTensorType as FloatTensorType, Int64TensorType as Int64TensorType, SequenceType as SequenceType, StringTensorType as StringTensorType
from .utils import check_input_and_output_numbers as check_input_and_output_numbers, check_input_and_output_types as check_input_and_output_types

def calculate_linear_classifier_output_shapes(operator) -> None: ...
def calculate_linear_regressor_output_shapes(operator) -> None: ...
