from .container import ModelComponentContainer as ModelComponentContainer
from .data_types import FloatType as FloatType, Int64Type as Int64Type, StringType as StringType, TensorType as TensorType
from .interface import OperatorBase as OperatorBase, ScopeBase as ScopeBase
from .onnx_ex import get_maximum_opset_supported as get_maximum_opset_supported, make_model_ex as make_model_ex
from .optimizer import optimize_onnx as optimize_onnx
from .registration import get_converter as get_converter, get_shape_calculator as get_shape_calculator
from _typeshed import Incomplete
from collections.abc import Generator

class Variable:
    raw_name: Incomplete
    onnx_name: Incomplete
    scope: Incomplete
    type: Incomplete
    is_fed: Incomplete
    is_root: Incomplete
    is_leaf: Incomplete
    is_abandoned: bool
    raw_params: Incomplete
    def __init__(self, raw_name, onnx_name, scope, type=None) -> None: ...
    @property
    def full_name(self): ...

class Operator(OperatorBase):
    onnx_name: Incomplete
    scope: Incomplete
    type: Incomplete
    raw_operator: Incomplete
    inputs: Incomplete
    outputs: Incomplete
    is_evaluated: Incomplete
    is_abandoned: bool
    target_opset: Incomplete
    def __init__(self, onnx_name, scope, type, raw_operator, target_opset) -> None: ...
    @property
    def full_name(self): ...
    @property
    def input_full_names(self): ...
    @property
    def output_full_names(self): ...
    @property
    def original_operator(self): ...
    def infer_types(self) -> None: ...

class Scope(ScopeBase):
    name: Incomplete
    parent_scopes: Incomplete
    onnx_variable_names: Incomplete
    onnx_operator_names: Incomplete
    target_opset: Incomplete
    variable_name_mapping: Incomplete
    variables: Incomplete
    operators: Incomplete
    def __init__(self, name, parent_scopes=None, variable_name_set=None, operator_name_set=None, target_opset=None) -> None: ...
    def get_onnx_variable_name(self, seed): ...
    def get_unique_variable_name(self, seed): ...
    def get_unique_operator_name(self, seed): ...
    def find_sink_variables(self): ...
    def declare_local_variable(self, raw_name, type=None, prepend: bool = False): ...
    def get_local_variable_or_declare_one(self, raw_name, type=None): ...
    def declare_local_operator(self, type, raw_model=None): ...
    def delete_local_operator(self, onnx_name) -> None: ...
    def delete_local_variable(self, onnx_name) -> None: ...

class Topology:
    scopes: Incomplete
    raw_model: Incomplete
    scope_names: Incomplete
    variable_name_set: Incomplete
    operator_name_set: Incomplete
    initial_types: Incomplete
    metadata_props: Incomplete
    default_batch_size: Incomplete
    target_opset: Incomplete
    custom_conversion_functions: Incomplete
    custom_shape_calculators: Incomplete
    root_names: Incomplete
    def __init__(self, model, default_batch_size: int = 1, initial_types=None, reserved_variable_names=None, reserved_operator_names=None, target_opset=None, custom_conversion_functions=None, custom_shape_calculators=None, metadata_props=None) -> None: ...
    def get_unique_scope_name(self, seed): ...
    def declare_scope(self, seed, parent_scopes=None): ...
    def unordered_operator_iterator(self) -> Generator[Incomplete]: ...
    def unordered_variable_iterator(self) -> Generator[Incomplete]: ...
    def find_root_and_sink_variables(self): ...
    def topological_operator_iterator(self) -> Generator[Incomplete, None, Incomplete]: ...
    def rename_variable(self, old_name, new_name) -> None: ...
    def compile(self) -> None: ...

def convert_topology(topology, model_name, doc_string, target_opset, targeted_onnx=None, channel_first_inputs=None): ...
