def sparkml_installed(): ...
def sklearn_installed(): ...
def skl2onnx_installed(): ...
def coreml_installed(): ...
def keras2onnx_installed(): ...
def torch_installed(): ...
def caffe2_installed(): ...
def libsvm_installed(): ...
def lightgbm_installed(): ...
def xgboost_installed(): ...
def h2o_installed(): ...
def hummingbird_installed(): ...
def get_producer(): ...
def get_producer_version(): ...
def get_domain(): ...
def get_model_version(): ...
def is_numeric_type(item): ...
def is_string_type(item): ...
def cast_list(type, items): ...
def convert_to_python_value(var): ...
def convert_to_python_default_value(var): ...
def convert_to_list(var): ...
def check_input_and_output_numbers(operator, input_count_range=None, output_count_range=None) -> None: ...
def check_input_and_output_types(operator, good_input_types=None, good_output_types=None) -> None: ...
