name: Lint Python code with Ruff & mypy

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vs-versions: [70]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up VapourSynth ${{ matrix.vs-versions }}
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: ${{ matrix.vs-versions }}

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt -r requirements-dev.txt

      - name: Running ruff
        run: uv run ruff check .

      - name: Running mypy on vstools
        run: uv run mypy vstools
