name: Test Python code

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/**'
      - '**.py'
  pull_request:
    paths:
      - '.github/actions/**'
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vs-versions: [67]
        python-version: ['3.10', '3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: qoomon/actions--context@v2
        id: context
      - uses: tj-actions/branch-names@v8
        id: branch-names

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up VapourSynth ${{ matrix.vs-versions }}
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: ${{ matrix.vs-versions }}

      - name: Set up vszip
        uses: ./.github/actions/setup-vszip
        with:
          vszip-version: 5

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt -r requirements-dev.txt

      - name: Running tests
        run: uv run pytest --cov-report=term-missing:skip-covered --cov=vskernels --cov=vstools tests

      - name: Convert coverage report to cobertura
        run: uv run coverage xml

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
        with:
          file: coverage.xml
          format: cobertura

      - name: Post webhook for failure
        if: failure()
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-url: ${{ steps.context.outputs.job_log_url }}
          embed-title: "[${{ github.event.repository.name }}] ${{ steps.context.outputs.job }} failed on ${{ steps.branch-names.outputs.current_branch }}"
          username: "GitHub - ${{ github.repository }}"
          avatar-url: https://github.githubassets.com/favicons/favicon.png
